server:
  port: ${PORT}

spring:
  cloud:
    config:
      server:
        #native:
        #search-locations: file:///${user.home}/ead/authuser,  file:///${user.home}/ead/course
        git:
          uri: 'https://github.com/edersonjseder/ead-config-server-repo'
          default-label: main
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
  #Datasource
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non-contextual-creation: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

encrypt:
  key: 855bf60361dd70d1bf20eeea92328b14299cad3b8df207c42ed3506f0767a7dcc45af81bc2163dd8a56d480da1c51ac98f50ec4aa0fdf5590b1daf923d792406

ead:
  config-server:
    username: ${CONFIG_SERVER_USERNAME}
    password: ${CONFIG_SERVER_PASSWORD}
    authority: ${CONFIG_SERVER_AUTHORITY}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${APP_DOMAIN_NAME}
    non-secure-port: 80
